/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityFeed: typeof import('./src/components/dashboard/ActivityFeed.vue')['default']
    AlertsTable: typeof import('./src/components/dashboard/AlertsTable.vue')['default']
    AppHeader: typeof import('./src/components/layouts/partials/AppHeader.vue')['default']
    AppMenu: typeof import('./src/components/layouts/partials/AppMenu.vue')['default']
    AppSidebar: typeof import('./src/components/layouts/partials/AppSidebar.vue')['default']
    AppUserMenu: typeof import('./src/components/layouts/partials/AppUserMenu.vue')['default']
    AsyncContent: typeof import('./src/components/shared/AsyncContent.vue')['default']
    AuthBrandPanel: typeof import('./src/components/auth/AuthBrandPanel.vue')['default']
    AuthFormField: typeof import('./src/components/auth/AuthFormField.vue')['default']
    AuthLayout: typeof import('./src/components/layouts/AuthLayout.vue')['default']
    AuthServerError: typeof import('./src/components/auth/AuthServerError.vue')['default']
    BaseAlert: typeof import('./src/components/atoms/feedback/BaseAlert.vue')['default']
    BaseAvatar: typeof import('./src/components/atoms/display/BaseAvatar.vue')['default']
    BaseBadge: typeof import('./src/components/atoms/display/BaseBadge.vue')['default']
    BaseButton: typeof import('./src/components/atoms/buttons/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/atoms/cards/BaseCard.vue')['default']
    BaseConfirmDialog: typeof import('./src/components/atoms/overlays/BaseConfirmDialog.vue')['default']
    BaseDataTable: typeof import('./src/components/tables/BaseDataTable.vue')['default']
    BaseDateRangePicker: typeof import('./src/components/atoms/pickers/BaseDateRangePicker.vue')['default']
    BaseDrawer: typeof import('./src/components/atoms/overlays/BaseDrawer.vue')['default']
    BaseEmptyState: typeof import('./src/components/atoms/feedback/BaseEmptyState.vue')['default']
    BaseErrorState: typeof import('./src/components/atoms/feedback/BaseErrorState.vue')['default']
    BaseInput: typeof import('./src/components/atoms/inputs/BaseInput.vue')['default']
    BaseModal: typeof import('./src/components/atoms/overlays/BaseModal.vue')['default']
    BaseMultiSelect: typeof import('./src/components/atoms/selects/BaseMultiSelect.vue')['default']
    BasePagination: typeof import('./src/components/atoms/navigation/BasePagination.vue')['default']
    BasePasswordInput: typeof import('./src/components/atoms/inputs/BasePasswordInput.vue')['default']
    BaseRichTextEditor: typeof import('./src/components/atoms/inputs/BaseRichTextEditor.vue')['default']
    BaseSearchInput: typeof import('./src/components/atoms/inputs/BaseSearchInput.vue')['default']
    BaseSelect: typeof import('./src/components/atoms/selects/BaseSelect.vue')['default']
    BaseSkeleton: typeof import('./src/components/atoms/feedback/BaseSkeleton.vue')['default']
    BaseSpinner: typeof import('./src/components/atoms/feedback/BaseSpinner.vue')['default']
    BaseStaffTable: typeof import('./src/components/shared/BaseStaffTable.vue')['default']
    BaseTableActions: typeof import('./src/components/tables/BaseTableActions.vue')['default']
    BaseTableEmpty: typeof import('./src/components/tables/BaseTableEmpty.vue')['default']
    BaseTag: typeof import('./src/components/atoms/display/BaseTag.vue')['default']
    BaseTextarea: typeof import('./src/components/atoms/inputs/BaseTextarea.vue')['default']
    CheckboxGroup: typeof import('./src/components/shared/CheckboxGroup.vue')['default']
    ColumnSelectorButton: typeof import('./src/components/tables/ColumnSelectorButton.vue')['default']
    ColumnSelectorDrawer: typeof import('./src/components/tables/ColumnSelectorDrawer.vue')['default']
    ConfirmDialog: typeof import('./src/components/shared/ConfirmDialog.vue')['default']
    ContactsInput: typeof import('./src/components/forms/ContactsInput.vue')['default']
    EmptyState: typeof import('./src/components/shared/EmptyState.vue')['default']
    ExportFormatSelector: typeof import('./src/components/shared/ExportFormatSelector.vue')['default']
    FilterBar: typeof import('./src/components/shared/FilterBar.vue')['default']
    FiltersCol: typeof import('./src/components/filters/FiltersCol.vue')['default']
    FiltersRow: typeof import('./src/components/filters/FiltersRow.vue')['default']
    FiltersWrapper: typeof import('./src/components/filters/FiltersWrapper.vue')['default']
    FormFieldWrapper: typeof import('./src/components/forms/FormFieldWrapper.vue')['default']
    FormFooter: typeof import('./src/components/forms/FormFooter.vue')['default']
    FormSection: typeof import('./src/components/forms/FormSection.vue')['default']
    MetricCard: typeof import('./src/components/dashboard/MetricCard.vue')['default']
    PageHeader: typeof import('./src/components/shared/PageHeader.vue')['default']
    PermissionGuard: typeof import('./src/components/shared/PermissionGuard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./src/components/filters/SearchFilter.vue')['default']
    TablePagination: typeof import('./src/components/shared/TablePagination.vue')['default']
    TrendChart: typeof import('./src/components/dashboard/TrendChart.vue')['default']
  }
}
